### ISSUE TITLE
Create pull request/issue template

### ISSUE THREAD

**Issue by Njong392** [dailydotdev/docs#110]
With a PR or issue template, it's easier for contributors to provide structured issues and pull requests. That way, we know what they are fixing, where they are fixing it, screenshots and all the like.

**Comment by GrahamTheDev** [comment]
Great suggestion!

I will have to have a think about this one, most items in the docs don't conform to a standard pattern and a lot of them time we do not need debugging information as the site is simple.

But, added to the backlog of things to discuss internally and see what we think would work 👍
