### ISSUE TITLE
[FEATURE] Play YT videos on the same page

### ISSUE THREAD

**Issue by Susmita-Dey** [dailydotdev/docs#114]
I want to improve the docs website by making the YT videos played by the users on the same page without leaving the page.

**Comment by GrahamTheDev** [comment]
Hey, is there a particular video / location this is happening for you?

Any inline videos should play within the page, but it could be some older videos (before we played them inline) have not been updated.

If you want to take this issue and submit a PR let me know!

**Comment by Susmita-Dey** [comment]
@GrahamTheDev The videos which are already added in the docs are taking to Youtube when I tried to click on it. I was thinking to play them inside the website rather than redirecting them. I can take up this issue.

**Comment by GrahamTheDev** [comment]
Thanks Susmita. I cannot replicate this, they all play inline for me and can be made full screen. 

Could you let me know what browser you are using?

In the mean time i am looking into adding a Lightbox to improve the experience, so it was a great suggestion!

**Comment by vydyas** [comment]
I can work on this issue as part of hacktoberfest.

**Comment by SaarthakMaini** [comment]
Hello @Susmita-Dey ,

I would like to contribute to this issue

Thank you!

**Comment by FrancescoXX** [comment]
go for it @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@FrancescoXX Thanks for assigning. I'll make a PR soon.

**Comment by Susmita-Dey** [comment]
@FrancescoXX Seems like the issue have been fixed by someone. Closing this as of now. I'll try to contribute after finding some other issues.
