### ISSUE TITLE
Word breaks for small screen

### ISSUE THREAD

**Issue by developer-diganta** [dailydotdev/docs#117]
I noticed that the word installation was broken when I tried it on a small screen. Can I work on this to fix it?
![image](https://user-images.githubusercontent.com/65999534/189742397-1c5ae983-f6a2-43a0-8419-bcec3c4eaac3.png)

**Comment by GrahamTheDev** [comment]
Thank you for this, I am looking into it and should have it resolved soon!

**Comment by GrahamTheDev** [comment]
Thanks, this is now resolved in the latest update.
