### ISSUE TITLE
No tags in the version in the pakage.json

### ISSUE THREAD

**Issue by afnanabdulvasay-234** [dailydotdev/docs#123]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/100799939/193301938-86d0c496-10f6-464d-aa4c-3fdb112f7317.png">

**Comment by eddiejaoude** [comment]
Release will also create a tag and show on the homepage of the repo

<img width="670" alt="Screenshot 2022-09-30 at 16 17 40" src="https://user-images.githubusercontent.com/624760/193302433-4fc8c0a3-ebb5-4e11-aeae-609fbfe00dbc.png">
