### ISSUE TITLE
docs: issue templates

### ISSUE THREAD

**Issue by eddiejaoude** [dailydotdev/docs#129]
Issue template ideas

- bugs
- new feature
- ...

https://github.com/EddieHubCommunity/LinkFree/tree/main/.github/ISSUE_TEMPLATE

**Comment by Niravprajapati1** [comment]
Can i contribute to this ?

**Comment by vish-han** [comment]
I would love to contribute to this issue, Please assign me😊

**Comment by FrancescoXX** [comment]
closing as it's a duplicate
