### ISSUE TITLE
Bugs and Templates

### ISSUE THREAD

**Issue by money8203** [dailydotdev/docs#137]
<html>
<body>
<article class="markdown-body pb-3" style="box-sizing: border-box; display: block; padding-bottom: 16px !important; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; line-height: 1.5; overflow-wrap: break-word;">

Name | About | Labels | Assignees
-- | -- | -- | --
🐛 Bug | Report an issue to help improve the project. | 🛠 goal: fix |  

</article><table class="d-block" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; display: block !important;"><tbody class="d-block" style="box-sizing: border-box; display: block !important;"><tr class="d-block" style="box-sizing: border-box; display: block !important;"><td class="d-block issue-form-body" style="box-sizing: border-box; padding: 0px; display: block !important;"><div class="form-group required" style="box-sizing: border-box; margin-top: 0px !important; margin-right: 0px; margin-bottom: 15px; margin-left: 0px;"><div class="form-group-header" style="box-sizing: border-box; margin: 0px 0px 6px;"><label required="required" class="h3" aria-required="true" for="issue_form_description" style="box-sizing: border-box; font-weight: 600 !important; font-size: 20px !important; position: static;">Description</label><div id="description-description" data-view-component="true" class="markdown-body note mb-2 text-small" style="box-sizing: border-box; min-height: 17px; margin-top: 4px; margin-right: 0px; margin-bottom: 8px !important; margin-left: 0px; font-size: 16px; color: var(--color-fg-muted); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; line-height: 1.5; overflow-wrap: break-word;"><p style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 0px !important;">A brief description of the question or issue, also include what you tried and what didn't work</p></div></div><div class="form-group-body" style="box-sizing: border-box;"><textarea class="issue-form-textarea form-control js-structured-issue-textarea-expander js-session-resumable" required="required" disabled="disabled" aria-describedby="description-description" data-test-selector="issue-form-textarea-element" name="issue_form[description]" id="issue_form_description" style="box-sizing: border-box; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: inherit; margin: 0px 5px 0px 0px; overflow: auto; padding: 8px 12px; color: var(--color-primer-fg-disabled); vertical-align: middle; background-color: var(--color-canvas-inset); background-repeat: no-repeat; background-position: right 8px center; border-color: var(--color-border-default); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px; box-shadow: var(--color-primer-shadow-inset); transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; height: 200px; min-height: 200px; -webkit-text-fill-color: var(--color-primer-fg-disabled); opacity: 1; width: 1134px; max-width: 100%;"></textarea><div class="js-wysiwyg-target" style="box-sizing: border-box;"></div></div></div><div class="form-group " style="box-sizing: border-box; margin: 15px 0px;"><div class="form-group-header" style="box-sizing: border-box; margin: 0px 0px 6px;"><label class="h3" aria-required="false" for="issue_form_screenshots" style="box-sizing: border-box; font-weight: 600 !important; font-size: 20px !important; position: static;">Screenshots</label><div id="description-screenshots" data-view-component="true" class="markdown-body note mb-2 text-small" style="box-sizing: border-box; min-height: 17px; margin-top: 4px; margin-right: 0px; margin-bottom: 8px !important; margin-left: 0px; font-size: 16px; color: var(--color-fg-muted); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; line-height: 1.5; overflow-wrap: break-word;"><p style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 0px !important;">Please add screenshots if applicable</p></div></div><div class="form-group-body" style="box-sizing: border-box;"><textarea class="issue-form-textarea form-control js-structured-issue-textarea-expander js-session-resumable" disabled="disabled" aria-describedby="description-screenshots" data-test-selector="issue-form-textarea-element" name="issue_form[screenshots]" id="issue_form_screenshots" style="box-sizing: border-box; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: inherit; margin: 0px 5px 0px 0px; overflow: auto; padding: 8px 12px; color: var(--color-primer-fg-disabled); vertical-align: middle; background-color: var(--color-canvas-inset); background-repeat: no-repeat; background-position: right 8px center; border-color: var(--color-border-default); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px; box-shadow: var(--color-primer-shadow-inset); transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; height: 200px; min-height: 200px; -webkit-text-fill-color: var(--color-primer-fg-disabled); opacity: 1; width: 1134px; max-width: 100%;"></textarea><div class="js-wysiwyg-target" style="box-sizing: border-box;"></div></div></div><div class="form-group " style="box-sizing: border-box; margin: 15px 0px;"><div class="form-group-header" style="box-sizing: border-box; margin: 0px 0px 6px; color: rgb(240, 243, 246); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(10, 12, 16); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label class="h3" aria-required="false" for="issue_form_extrainfo" style="box-sizing: border-box; font-weight: 600 !important; font-size: 20px !important; position: static;">Additional information</label><div id="description-extrainfo" data-view-component="true" class="markdown-body note mb-2 text-small" style="box-sizing: border-box; min-height: 17px; margin-top: 4px; margin-right: 0px; margin-bottom: 8px !important; margin-left: 0px; font-size: 16px; color: var(--color-fg-muted); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; line-height: 1.5; overflow-wrap: break-word;"><p style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 0px !important;">Is there anything else we should know about this bug?</p></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by money8203** [comment]
name: Build
on:
  push:
    paths:
      - public/**
      - src/**
      - cypress/**
  pull_request:
    paths:
      - public/**
      - src/**
      - cypress/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run lint
      - name: run build
        run: npm run build

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci

-       - name: run tests

        run: npm run test:e2e

**Comment by FrancescoXX** [comment]
duplicated
