### ISSUE TITLE
Docs: Fix links 

### ISSUE THREAD

**Issue by GoodnessEzeh** [dailydotdev/docs#14]
FIX LINKS: The links seem to broken. I keep getting "404 Error" when I tried navigating through them.

**Comment by FrancescoXX** [comment]
Hi GoodneesEzeh, can you please point out which links are brtoken? thank you!

**Comment by GoodnessEzeh** [comment]
Thank you for the reply. I am referring to the web-links on the into.md file. You may navigate to https://github.com/dailydotdev/docs/blob/main/docs/intro.md to get to the file.

**Comment by FrancescoXX** [comment]
thank you for your feedback. this is because the links are intended to be navigated directly from the docs and not inside the gh repository. btw we will check this, thank you!
