### ISSUE TITLE
docs: missing two preferences under customization

### ISSUE THREAD

**Issue by vikasganiga05** [dailydotdev/docs#149]
### Description

Under `Customization > Preferences` the documentation for `Show Weekly Goal widget` and `Enable companion` are missing. 

### Screenshots

> DailyDotDev Extension :point_down: 
>
> ![image](https://user-images.githubusercontent.com/74750414/193502442-a65a7003-eaef-43c9-bb41-2c820139eecc.png)

> DailyDotDev Docs Site :point_down: 
>
> ![image](https://user-images.githubusercontent.com/74750414/193502603-df489c6c-dbd3-404c-9de8-f60dd564d6a2.png)

### Additional information

This need to fix as soon as possible.

**Comment by thisiskaransgit** [comment]
Hey, @vikasganiga05 I would like to work on this issue!

**Comment by vikasganiga05** [comment]
> Hey, @vikasganiga05 I would like to work on this issue!

Yeah sure, go ahead:+1:

**Comment by thisiskaransgit** [comment]
Hey @vikasganiga05, Kindly review the PR

**Comment by FrancescoXX** [comment]
assigned to @GrahamTheDev as we are the only ones with access to cloudinary

**Comment by FrancescoXX** [comment]
closing this has it has been updated
