### ISSUE TITLE
Improve Card Design

### ISSUE THREAD

**Issue by Swati002** [dailydotdev/docs#151]
Assign this issue to me

**Comment by GrahamTheDev** [comment]
We would need more details about what you are planning on changing, could you do a mockup first.

Could you also expand on whether this is a video card design update, a landing page design update, or both please.

**Comment by hazardemircan** [comment]
> Hey @GrahamTheDev i can improve the card design. I wanna do something like this, what do you think? I did just in a few minutes, so don't take this too serious this was just to show my idea.
> 
>  hello-from-dailydev-dailydev-google-chrome-2022-10-10-20-30-34-trim-mwvzbmqq_EdypUXRq.mp4

The other idea that comes mind is, card hover can be 3D

**Comment by FrancescoXX** [comment]
we asked the design team and it's not part of our branding
