### ISSUE TITLE
Need Dark / Light Mode Toggler for Mobile Screens as well.

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [dailydotdev/docs#152]
### Description

Currently Theme toggler button is available for desktop devices only, hence it would be great if it is available for mobile devices as well.

### Screenshots

<img width="1142" alt="Screenshot 2022-10-04 at 1 47 21 PM" src="https://user-images.githubusercontent.com/93585735/193769595-ffd8c047-fdf7-461a-a12e-80c7aad495a4.png">

### Additional information

Assign the issue to me so I can fix it.

**Comment by Mayank1170** [comment]
Hey @dailydotdev can you please assign this issue to me..

**Comment by GrahamTheDev** [comment]
@Mayank1170 yours if you want it! Please use the same switch as displays on the desktop version.

**Comment by FrancescoXX** [comment]
@Mayank1170 do you still wanna work on this ?

**Comment by Mayank1170** [comment]
@FrancescoXX if you want, then you may carry it on

**Comment by vedant-z** [comment]
@FrancescoXX May I try this?

**Comment by KarthikRaju391** [comment]
@FrancescoXX, can I try it out??

**Comment by ShruAgarwal** [comment]
Hey @Vedant-Manjrekar 👋
The toggler is already available on Mobile screens. Do you wish to change its position and align it before the **Search icon** just like in the desktop version? 🤔

![mobile_toggle](https://user-images.githubusercontent.com/82811717/227206834-2e85e2b4-ad10-4314-b0c8-13a8b3c15190.gif)

**Comment by Vedant-Manjrekar** [comment]
Yes, from UX point of view it seems more practical to have the Toggler next to the search icon or on the main navbar screen in general.

**Comment by himanshu1221** [comment]
hey @GrahamTheDev if this issue is open I would love to work on the suggested design by @Vedant-Manjrekar

**Comment by santosh-kuchetti** [comment]
I have resolved and raising the PR

**Comment by FrancescoXX** [comment]
for now we are happy with our UI, thanks
