### ISSUE TITLE
feat: search bar border fix in dark mode

### ISSUE THREAD

**Issue by Jonnie-Dev** [dailydotdev/docs#155]
### Description

On switching to dark mode, the border on the search bar disappears due to its color matching the background color for dark mode. Would love to have this assigned to me so I can fix it.

### Screenshots

![Screenshot (158)](https://user-images.githubusercontent.com/73708569/194124521-4aea9d59-f0c5-4572-8abd-022da183d739.png)

**Comment by YuriDevAT** [comment]
Hi. I would like to work on this issue.

**Comment by Johnnyteck** [comment]
@FrancescoXX kindly assign to one of us 😁

**Comment by FrancescoXX** [comment]
we have to check this with the design team

**Comment by FrancescoXX** [comment]
for now we are happy with this design
