### ISSUE TITLE
Add CONTRIBUTING.md & CODE_OF_CONDUCT.md into this Project.

### ISSUE THREAD

**Issue by syedsohan** [dailydotdev/docs#16]
I guess it would be great if we add **CONTRIBUTING.md & CODE_OF_CONDUCT.md** in this Project for first-timers as they will look after this two in this project. I know there is already  CONTRIBUTING.md & CODE_OF_CONDUCT.md in [.github](https://github.com/dailydotdev/.github) this repository.

**Comment by FrancescoXX** [comment]
Thank you for your feedback!

**Comment by syedsohan** [comment]
> Thank you for your feedback!

🙂
