### ISSUE TITLE
Add contributor label to readme file 

### ISSUE THREAD

**Issue by Hariom8799** [dailydotdev/docs#160]
![194721540-e2c06f16-cdcf-4d0d-8f58-964f96d5fd95](https://user-images.githubusercontent.com/76242202/194739271-5c7028fd-7b9f-45e5-a78b-4970c5d4075d.png)
Like that

**Comment by Hariom8799** [comment]
Pls assign me

**Comment by YuriDevAT** [comment]
Hi. I would like to work on this issue.

**Comment by FrancescoXX** [comment]
done already
