### ISSUE TITLE
Search bar not working on Mobile

### ISSUE THREAD

**Issue by Eugene44-hub** [dailydotdev/docs#163]
### Description

When the search icon is clicked the search field shows behind a pop up as shown in the screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/75457464/195475233-d6a8ac32-f0ed-4c68-a529-5cefad4e11cd.png)

### Additional information

It doesn't allow get a view of what they typing

**Comment by Eugene44-hub** [comment]
Please can you kindly assign this to me

**Comment by GrahamTheDev** [comment]
Fixed by #161, thanks for reporting!
