### ISSUE TITLE
Footer link colors seem wrong

### ISSUE THREAD

**Issue by rebelchris** [dailydotdev/docs#164]
### Description
The footer links at the bottom of the pages are red, not sure if it's in line with the daily.dev branding.

### Screenshots
![Screenshot 2022-10-13 at 07 18 49](https://user-images.githubusercontent.com/554874/195508226-b05670c5-c2ab-4288-8c1d-150d22b712aa.png)

### Additional information

Page used as example:
https://docs.daily.dev/docs/how-does-daily-dev-work/reputation

**Comment by AchmadAlli** [comment]
I don't know about the design language system (like rules that all contributors agreed on) but the problem is the color scheme, when I switch to dark mode, every anchor tag will be shown with the purple color and I switch to light mode, every anchor tag will be shown with red color

**Comment by Mayank1170** [comment]
@FrancescoXX Can we change the red color to Dark grey and put a round border around that ?

**Comment by FrancescoXX** [comment]
this has been fixed
