### ISSUE TITLE
[FEATURE] <want to change the color of star>

### ISSUE THREAD

**Issue by aivy45** [dailydotdev/docs#167]
### Description

In key feature block there is a star , but to change the color from  black to yellow it would look great.

**Comment by Rahul-Kumar-prog** [comment]
i would like to work on this please assign me.

**Comment by Rahul-Kumar-prog** [comment]
#168

**Comment by Rahul-Kumar-prog** [comment]
#169

**Comment by FrancescoXX** [comment]
we are not accepting this issue. thank you anyway.
