### ISSUE TITLE
Add Thanks to the all Contributors & Support in README.md

### ISSUE THREAD

**Issue by syedsohan** [dailydotdev/docs#17]
I know it is not mandatory but it would be good if we add two sections of Thanks to all Contributors and Support.

- Thanks to the all Contributors - Thanks a lot for spending your time helping with The official product docs daily.dev grow. Thanks a lot!
- Support - This project needs a ⭐️ from you. Don't forget to leave a star ⭐️

**Comment by FrancescoXX** [comment]
great feedback thanks you!

**Comment by avneesh0612** [comment]
I can work on this issue!

**Comment by avneesh0612** [comment]
Can you assign it to me? @FrancescoXX

**Comment by syedsohan** [comment]
> great feedback thanks you!

Thanks for the response. I can work on this issue as well if you want. 🙂

**Comment by FrancescoXX** [comment]
this would be awesome @avneesh0612 and @syedsohan ! please work on this

**Comment by syedsohan** [comment]
> this would be awesome @avneesh0612 and @syedsohan ! please work on this

I have opened a PR for this issue. Check out the PR #22

**Comment by FrancescoXX** [comment]
done! We can close this now
