### ISSUE TITLE
typo: we are tiktok

### ISSUE THREAD

**Issue by jessej-samuel** [dailydotdev/docs#170]
### Description

The promotion card reads "We are TikTok". I think it's supposed to be "We are on Tiktok"

### Screenshots

![image](https://user-images.githubusercontent.com/72020411/200134645-b127599a-ebac-47a9-aea8-42739b217d11.png)

**Comment by nimrodkra** [comment]
@jessej-samuel fixed! Thank you for noticing and raising this issue.
