### ISSUE TITLE
Clarification of documentations

### ISSUE THREAD

**Issue by wagenrace** [dailydotdev/docs#175]
### Description

Within [content-guidelines](https://github.com/dailydotdev/docs/tree/main/docs/for-content-creators/content-guidelines.md) it states "❌ It is a personal blog (global thought-leaders excluded)."
Does this mean that every blog written by yourself will be rejected, or is a personal blog more narrow in its definition?

Scenario 1: I write a blog about my thoughts about ChatGPT (I am NOT a global thought-leader), this will be rejected
Scenario 2: I write a blog about how to use ChatGPT for writing python code, is this a personal blog?
Scenario 3: I scout a blog of someone's (I do not know) thoughts about ChatGPT, will this be a personal blog?

Summary questions:
I there a scenario where I can share a blog/article I wrote myself on daily.dev?
Are all opinion pieces of none global thought-leaders automatically rejected?

**Comment by nimrodkra** [comment]
Hi @wagenrace when we say "personal blog" we don't mean an individual article but rather the entire publication. If you're interested in submitting individual articles the feature you're looking for is called [Community Picks](https://docs.daily.dev/docs/key-features/community-picks). Using that feature community members (with more the 250 reputation points) can scout and submit specific links to the feed.

**Comment by wagenrace** [comment]
Hi @nimrodkra, I am indeed talking about community pick, but the documentation does link to content-guidelines at the bottom. So I assumed the guidelines for community picks and new sources is the same.

What I want to know is, is it okay to submit my own technical blog in the community pick?

![image](https://user-images.githubusercontent.com/15228140/222756437-077700d3-f6e6-4bf5-b863-31f0a3f2c460.png)

**Comment by nimrodkra** [comment]
Here are the specific guidelines for community picks:
https://docs.daily.dev/docs/how-does-daily-dev-work/community-picks-submission-guidelines

Community Picks was made to highlight amazing articles from our community,
not self-promotion. So submitting your own links isn’t welcomed tbh.

Here’s more info about ways in which you can [get your articles listed on
daily.dev](
https://docs.daily.dev/docs/how-does-daily-dev-work/how-to-get-featured).
