### ISSUE TITLE
Feat: Update Footer

### ISSUE THREAD

**Issue by himanshu1221** [dailydotdev/docs#184]
### Description

The current footer need to be updated as it's very plain and simple 

### Screenshots

https://user-images.githubusercontent.com/32031706/233824802-667bcddd-2b25-4ea8-8ec4-5a72d746644a.mp4

### Additional information

If mentainer found this issue relevant then they may provide me the relevant design i would love to work on it

**Comment by FrancescoXX** [comment]
thank you, for now we like this format.
