### ISSUE TITLE
Search Component : Focus State UI of Search Input wasn't looks good

### ISSUE THREAD

**Issue by KarthickSakthi** [dailydotdev/docs#188]
### Description

When I click the Search Option in Navbar, will get  a Search Component, in that when i start typing to search. The focus state of that input Search component wasn't looks good

### Screenshots

<img width="675" alt="Screenshot 2023-05-27 at 12 48 07 PM" src="https://github.com/dailydotdev/docs/assets/56196782/1b290993-ff91-4db8-9e1a-3042feb1c1c2">

### Additional information

The correct fix is:

<img width="647" alt="Screenshot 2023-05-27 at 12 55 36 PM" src="https://github.com/dailydotdev/docs/assets/56196782/dae201c7-fd53-43bd-a1c0-9f15054a8b05">

**Comment by KarthickSakthi** [comment]
I tried to give a pull request, but don't know, in which folder/file i need to work on.
Can any CodeOwners Kindly help on this, I will give a Pull request

**Comment by elidakirigo** [comment]
hi , I'd love to contribute to this issue if its still open.

**Comment by FrancescoXX** [comment]
assigned to @elidakirigo and @KarthickSakthi . please let me know who is up for working on this.

**Comment by KarthickSakthi** [comment]
@FrancescoXX ,  I will work on this issue, will give a PR. Thanks

**Comment by KarthickSakthi** [comment]
@FrancescoXX can you Kindly check and merge this PR: 
https://github.com/dailydotdev/docs/pull/198

I am waiting for a long time to contribute this issue to daily.dev , I've got response from you Side Yesterday only!
Kindly check and merge this!

Thanks

**Comment by FrancescoXX** [comment]
this has been fixed
