### ISSUE TITLE
[FEATURE] 1/ Remove FAQ section as it’s no longer maintained

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#208]
### Description

1/ Remove FAQ section as it’s no longer maintained

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/719dea69-d809-4872-8906-76728f51b822)

**Comment by 2div** [comment]
Hi , I have forked the repo and i want to work on this task.
can you give me some guide how to solve the issue ?

Thank you

**Comment by FrancescoXX** [comment]
steps:
- remove FAQ from the navbar
- remove the FAQ component 
- check if there's any dependency when removing the section

**Comment by Umesh9-prog** [comment]
hi @FrancescoXX i would like to work on this issue please assign me this issue under hacktoberfest label

**Comment by FrancescoXX** [comment]
assigned this to @Yashpsct010 (@Umesh9-prog you have another issue assigned)

**Comment by Umesh9-prog** [comment]
@FrancescoXX  thanks for assigning

**Comment by FrancescoXX** [comment]
@Yashpsct010 did you still want to work on this? otherwise we can assign this to @Umesh9-prog

**Comment by Yashpsct010** [comment]
Sorry I am currently not working on this. You can assign to someone else.

**Comment by NXKED** [comment]
@FrancescoXX alright, thanks will do

**Comment by Umesh9-prog** [comment]
hi @FrancescoXX can i work on these ?

**Comment by JanumalaAkhilendra** [comment]
please assign me this issue under hacktoberfest label

**Comment by NXKED** [comment]
PR already done
