### ISSUE TITLE
Remove video tips section as it’s no longer maintained

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#209]
### Description

Remove video tips section as it’s no longer maintained

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/1e184097-31be-4cb3-ae03-7afe3fb3a137)

**Comment by 2div** [comment]
Hi , I would like to work on this issue ?

**Comment by Umesh9-prog** [comment]
hi @FrancescoXX can u assign this issue to me under hacktoberfest label

**Comment by FrancescoXX** [comment]
done
