### ISSUE TITLE
Update the footer to make it look same as the landing page

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#211]
### Description

the docs footer looks like the screenshot below

![image](https://github.com/dailydotdev/docs/assets/18360871/b6206de5-fa4e-41e2-8241-7da539d8b5c3)

make it look the same style as the one in https://daily.de

![image](https://github.com/dailydotdev/docs/assets/18360871/c3e17991-14c9-42d2-982d-e8e300385629)

**Comment by vatan999** [comment]
Hey @FrancescoXX I want to work on this issue. If possible please assign it to me under hactoberfest tag.
Thanx

**Comment by FrancescoXX** [comment]
hey @vatan999 , assigned to you

**Comment by Yashpsct010** [comment]
please assign me this issue

**Comment by JanumalaAkhilendra** [comment]
please assign me this issue

**Comment by FrancescoXX** [comment]
@JanumalaAkhilendra do you still want to work on this?

**Comment by dhiraj1996** [comment]
Hello @FrancescoXX . I want to work on this issue can you please assign it to me and can you provide me more information?

**Comment by FrancescoXX** [comment]
@dhiraj1996 this has been solved already. Thanks
