### ISSUE TITLE
Merge "Integrations" section in the main bookmarks ddoc

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#212]
### Description

Merge this docs into the main bookmarks doc. No need for a special doc just for that

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/69eb7ebc-12d2-494d-8216-c63dff42dc18)

**Comment by paaggeli** [comment]
Hi , I'm interested in fixing this issue.
Could you please assign this issue to me? 
I would be happy to contribute.

**Comment by FrancescoXX** [comment]
assigned to you @paaggeli
