### ISSUE TITLE
Update Customization-layoout section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#213]
### Description

Update this section, including all screenshots needed

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/d1352923-c82a-4f25-8f7b-4703a4f1db0d)

**Comment by AlphaKappa44** [comment]
Hi, I could work on this but it looks like screenshots are already there!
Maybe i am missing something?  Tell me more and assign it to me i would like to help.

![image](https://github.com/dailydotdev/docs/assets/62958796/acedd535-718b-46b8-8d30-b48ae94a15f9)

**Comment by nimrodkra** [comment]
Hey, this page has been recently revamped already. No need for further improvements, thank you :)

**Comment by FrancescoXX** [comment]
Assigned to you @AlphaKappa44
