### ISSUE TITLE
Update "Search button" design on dark mode

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#214]
### Description

- Improve the color contrast on the search design

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/1046fdf3-df87-41df-992e-cb430d8d03c0)

![image](https://github.com/dailydotdev/docs/assets/18360871/e465872d-37b1-4392-b59a-fc74da18f03e)

**Comment by FrancescoXX** [comment]
solved for dark theme, to be done in light mode

**Comment by Umesh9-prog** [comment]
hi @FrancescoXX i am also working on this issue so if  possible assign this to me

**Comment by dominicOT** [comment]
Hi @FrancescoXX please assign me to this issue.

**Comment by FrancescoXX** [comment]
assigned to @dominicOT as Umesh is already working on another one
