### ISSUE TITLE
Editing post outside of type welcome_post and freeform is not allowed

### ISSUE THREAD

**Issue by regisBafutwabo** [dailydotdev/docs#225]
### Description

Whenever I tried to edit a post inside a squad I get this warning:
`Editing post outside of type welcome_post and freeform is not allowed`

**Comment by FrancescoXX** [comment]
@regisBafutwabo are you referring to the docs or the daily dev extension?

**Comment by FrancescoXX** [comment]
this is not related to the docs but the app itself
