### ISSUE TITLE
Incorrect Color for "Squads" Icon in Sidebar

### ISSUE THREAD

**Issue by paaggeli** [dailydotdev/docs#228]
### Description

Hi,

I noticed a small issue in the project's sidebar. The "Squads" icon has the wrong color, especially noticeable in the dark theme.

### Screenshots

![SquadsIcon](https://github.com/dailydotdev/docs/assets/18037753/529d67c8-87c5-4d52-9e36-4fc2d33012cb)

**Comment by paaggeli** [comment]
I would like to work on this issue.

**Comment by FrancescoXX** [comment]
you can go with that @paaggeli . please check the #230 icon

**Comment by Yashpsct010** [comment]
please assign me this issue in hacktoberfest label

**Comment by FrancescoXX** [comment]
assigned this to @paaggeli , if you can't work on this please let me know

**Comment by dominicOT** [comment]
hi @paaggeli , are you still working on this?

**Comment by paaggeli** [comment]
Hi @dominicOT, I have already created a pull request.

**Comment by paaggeli** [comment]
Hi @FrancescoXX, is it possible to label this issue with  hacktoberfest  label?
