### ISSUE TITLE
[FEATURE] update screenshot in the blocking tags section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#232]
### Description

one of the screenshots is not up to date

docs section:
https://docs.daily.dev/docs/setting-up-your-feed/blocking-tags-sources

please replace it with something like this

![image](https://github.com/dailydotdev/docs/assets/18360871/53709d5d-4050-41da-b505-b70c06589ec3)

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/ac6f46d3-9b66-4f24-abbe-5d8e7c020d4d)

![image](https://github.com/dailydotdev/docs/assets/18360871/e306e9ab-e628-4a4e-8971-0f3a8569e7c5)

**Comment by Shubhammete** [comment]
Hey!
I want to work on it
