### ISSUE TITLE
[FEATURE] bookmarks screenshot update

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#235]
### Description

update the screenshot in the bookmarks section

section link: https://docs.daily.dev/docs/key-features/bookmarks

old one: 
![image](https://github.com/dailydotdev/docs/assets/18360871/50850e24-cb63-4247-a97b-c242636865ab)

new one (example)
![image](https://github.com/dailydotdev/docs/assets/18360871/43625e31-3f76-43d5-8536-82ac646fea22)

**Comment by fazil-syed** [comment]
I would like to work on this and could you clarify what to update specifically.

**Comment by FrancescoXX** [comment]
the submenu looks different. please use the updated version (you cna check it by yourself on the app)

**Comment by fazil-syed** [comment]
> the submenu looks different. please use the updated version (you cna check it by yourself on the app)

I see that the images are hosted on daily-now-res.cloudinary.com. How do I upload the new screenshot on that so I can update the bookmarks page

**Comment by FrancescoXX** [comment]
just use github or any other service, no worries

**Comment by fazil-syed** [comment]
I have added the new screenshot. you can merge the pull request

**Comment by FrancescoXX** [comment]
done
