### ISSUE TITLE
[FEATURE] replace the screenshot in the customize section to show the current sub-menu

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#236]
### Description

please update the screenshot in this section.
it should include 5 options instead of 4

section link:
https://docs.daily.dev/docs/customize-your-feed/preferences

old
![image](https://github.com/dailydotdev/docs/assets/18360871/9f833822-372b-4316-861d-ca9a96c96180)

how it should look (example)
![image](https://github.com/dailydotdev/docs/assets/18360871/3b126ab0-ab22-4307-a5d6-da53458c5641)

**Comment by Jitulteron7** [comment]
hey @FrancescoXX could u assign me this task

**Comment by Jitulteron7** [comment]
@FrancescoXX  I found I link to the image that need to be changed :
![](https://daily-now-res.cloudinary.com/image/upload/v1695752384/docs-v2/Preferences.png
)
how to upload the new ScreenSot so that I can replace the link?

**Comment by Jitulteron7** [comment]
@FrancescoXX could u clear my doubt on the above query  ?

**Comment by FrancescoXX** [comment]
@Jitulteron7 you can upload the image wherever you want, I will take care of uploading it to cloudinary in the fguture

**Comment by Jitulteron7** [comment]
Great Thank you  @FrancescoXX.

**Comment by Jitulteron7** [comment]
hey @FrancescoXX  I have created a PR please look into it

**Comment by Jitulteron7** [comment]
Here is the result
![Screenshot 2023-10-17 at 7 59 29 PM](https://github.com/dailydotdev/docs/assets/58761652/f568dac3-df2b-4444-9283-5ef116b23f63)
