### ISSUE TITLE
[FEATURE] check the section and remove the [beta] tag form community pics

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#237]
### Description

please check this section, and remove the [beta] tag

https://docs.daily.dev/docs/how-does-daily-dev-work/how-to-get-featured

![image](https://github.com/dailydotdev/docs/assets/18360871/72aa29b0-961e-4f3e-abbd-8818141afa77)

**Comment by NXKED** [comment]
I would like to work on it

**Comment by FrancescoXX** [comment]
go for it

**Comment by FrancescoXX** [comment]
done
