### ISSUE TITLE
[FEATURE] missing icon on mobile view

### ISSUE THREAD

**Issue by NXKED** [dailydotdev/docs#249]
### Description

Responsive view - Community Icon is missing. 
Light + Dark mode

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/107938013/dfb9f946-621d-4413-a7cf-dc97f3c24c5f)
![image](https://github.com/dailydotdev/docs/assets/107938013/950d3676-0011-4041-8329-6e2eb6541b39)

### Additional information

If possible please assign me 

_No response_

**Comment by amitabh-sahu** [comment]
Please assign this to me.

**Comment by FrancescoXX** [comment]
assigned to @amitabh-sahu

**Comment by NXKED** [comment]
In the current version, besides the issue with the icon disappearing,
the icon sits next to "Community" and is not inside the FeatureList of the homeNavBox-module.
Just like 'Introduction' but unlike others with an icon.

See image: 

![image](https://github.com/dailydotdev/docs/assets/107938013/b1b9c3d4-7bbd-455e-9f20-85bb7f9e6b20)

Introduction & FeatureList-items: 

![image](https://github.com/dailydotdev/docs/assets/107938013/3abb9403-8044-4793-b59f-1991f310161b)

Without taking 'Introduction' + 'Community' and putting them inside of that List, the icon **_can_** be put where its supposed to be, but the highlighted area when hovering would look wrong. 

Another image to help visualize the issue: 

![image](https://github.com/dailydotdev/docs/assets/107938013/a2fdea7c-1ccc-4252-86c7-c80350c7033b)

---

So @FrancescoXX 

- [ ]  Just fix it as is - just correct the placement of the icon. 
- [ ]  Completely change it to be in the list?


@amitabh-sahu How would you proceed?
