### ISSUE TITLE
Search Area's Content and Icon Visibility in Hover Effect

### ISSUE THREAD

**Issue by iamRabia-N** [dailydotdev/docs#255]
### Description

The visibility of the search area's content and icon is very low, making their presence near zero. This is because the background color, the content, and the icon color are the same. This problem can be solved by adding contrast colors to the hover effect of the search area.

### Screenshots

**Current Design**

![img (1)](https://github.com/dailydotdev/docs/assets/115794049/1f83f0a4-eeed-46ad-a2e2-6c7cb51c2636)

**Expected Updated Design**

![img (2)](https://github.com/dailydotdev/docs/assets/115794049/bd82920e-7af6-4c50-bd17-6ac4b3b30fc7)

### Additional information

N/A

**Comment by fazil-syed** [comment]
can you assign this task to me?

**Comment by FrancescoXX** [comment]
@fazil-syed do you still want to work on this?
