### ISSUE TITLE
Editing squad handle name alert or message

### ISSUE THREAD

**Issue by khantwaikyaw** [dailydotdev/docs#260]
### Description

Hello, squad handle validation is now working well when creating a new squad. 
But not in editing or updating squad. Nothing is dispalyed if the squad handle doen't match the validation.

**Comment by FrancescoXX** [comment]
hi, this is more a feedback rather than an issue for the doc. Please refer to https://daily.dev/feedback

**Comment by khantwaikyaw** [comment]
Hello @FrancescoXX,

Noted with thanks. I'll care about labelling and tagging next time. I'd like to apologize for my poor experiences. Moreover, I probably have never been concerned with any projects before. 
But, honestly, I've cencerned with this repo because I love it. You let me get another experience and pointing of the mistake I made is also efficient for me.

Thanks for getting back to me.
