### ISSUE TITLE
[FEATURE] Add the collection section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#265]
### Description

refer to this https://app.daily.dev/posts/M0nIoAHkd

**Comment by FrancescoXX** [comment]
add a collection section in the "key feeatures"

add the subscribe (to collection) feature

![image](https://github.com/dailydotdev/docs/assets/18360871/5659908c-160b-4332-a02e-1c6dc316c08d)

**Comment by CBID2** [comment]
I can help with this @FrancescoXX! :)

**Comment by CBID2** [comment]
Hey @FrancescoXX. I'm still interested in working on this issue.

**Comment by FrancescoXX** [comment]
hey @CBID2 , thanks. assigned to you!
