### ISSUE TITLE
[FEATURE] Add "Watch video" related docs

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#267]
### Description

We relased a feature that allows to post youtube videos on the feed. 

Add a section or change the documentation accordingly 

https://app.daily.dev/posts/7yqkWkdLc

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/79bf5487-2547-434d-8cf5-477425da2822)

**Comment by CBID2** [comment]
Can I work on this @FrancescoX?

**Comment by FrancescoXX** [comment]
sure go for it @CBID2
