### ISSUE TITLE
[FEATURE] <add picture to documentation about video post>

### ISSUE THREAD

**Issue by CBID2** [dailydotdev/docs#278]
### Description

There needs to be a screenshot for the Video posts section of the documentation. 

### Screenshots

![screenshot of video feature](https://github.com/dailydotdev/docs/assets/105683440/8bbaec65-8c12-496c-85ac-66c9dcd515b9)

**Comment by FrancescoXX** [comment]
Thanks @CBID2 , wanna work on this? Or I can do that

**Comment by FrancescoXX** [comment]
done for now, this might be updated in the future. thanks @CBID2
