### ISSUE TITLE
[FEATURE] Add tags to articles

### ISSUE THREAD

**Issue by thlaure** [dailydotdev/docs#290]
### Description

Add tags on articles to find or filter them easily, like in Pocket

**Comment by FrancescoXX** [comment]
hi @thlaure , this is the repository for the docs. What do you mean by "adding tags" ?

**Comment by thlaure** [comment]
Hi!

Oh sorry, my bad...

Let me clarify my example regarding tags:

Imagine I've read an article about integrating React in a Symfony app, and I want to save it for future reference. So, I bookmark it on Daily.Dev and share it with my company squad. However, as time goes by, I accumulate a significant number of articles in my bookmarks and company squad, making it challenging to search for specific topics manually.

My suggestion is to implement a tag functionality that allows users to add relevant tags to articles. For example, for the aforementioned article, I could add tags such as #javascript, #php, #js, and #symfony. This way, when I want to find all the articles related to a specific topic, such as PHP, I can simply select the #php tag, and all the relevant articles will be displayed

**Comment by FrancescoXX** [comment]
hey @thlaure , thank you for the feedback but this is about the docs for daily.dev

So it should not be posted here, but rather here

https://daily.dev/feedback
