### ISSUE TITLE
Update the History section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#296]
### Description

Update the "Search History section" adding the 

- Reading History section tab
- Search History tab

### Screenshots

![image](https://github.com/dailydotdev/docs/assets/18360871/9d6ac1f2-73c8-4e0a-afd9-5f9dbc215d35)

**Comment by CBID2** [comment]
Can I be assigned to this @FrancescoXX?

**Comment by FrancescoXX** [comment]
Done Chrissy

**Comment by CBID2** [comment]
Hi @FrancescoXX! :) I made the PR. It's #318.
