### ISSUE TITLE
Update the "Search" 

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#300]
### Description

Update the "Search" section, based on the new changelog

https://app.daily.dev/posts/b8oM37UNt

**Comment by CBID2** [comment]
I'll do it @FrancescoXX

**Comment by FrancescoXX** [comment]
Hi Chrissy, @CBID2 , I already assigned you one, let me know if you also want to work on this one

Thank you!

**Comment by CBID2** [comment]
I do @FrancescoXX

**Comment by CBID2** [comment]
Hey @FrancescoXX. Are you going to assign this to me?

**Comment by FrancescoXX** [comment]
Hey @CBID2 , I assigned this to you, if you still want to work on it! we would also need a new screenshot
