### ISSUE TITLE
[FEATURE] Update the bookmarks sections

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#305]
### Description

The Bookmark section is outdated. Update it with the new procedure and images

https://docs.daily.dev/docs/key-features/bookmarks

**Comment by Gokilp** [comment]
can you please assign to me

**Comment by FrancescoXX** [comment]
hey @Gokilp , assigned this to you, thanks

**Comment by FrancescoXX** [comment]
hey @Gokilp , do you still want to work on this?

**Comment by Gokilp** [comment]
Yes I'm working the issue

**Comment by FrancescoXX** [comment]
thank, you let me know how I can help

**Comment by FrancescoXX** [comment]
hey @Gokilp , do you still want to work on this issue?

**Comment by FrancescoXX** [comment]
this one has been fixed by me
