### ISSUE TITLE
Update screenshots on the Density section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#315]
### Description

some screenshots are outdated here

https://docs.daily.dev/docs/customize-your-feed/density

**Comment by Gokilp** [comment]
can you please assign to me

**Comment by FrancescoXX** [comment]
assigned thank you

**Comment by tmsagarofficial** [comment]
I would love to work on this issue, @FrancescoXX .
Assign it to me so I can work on this.

**Comment by FrancescoXX** [comment]
assigned @tmsagarofficial , thank you!

**Comment by FrancescoXX** [comment]
done by https://github.com/dailydotdev/docs/commit/434d663606aef083c1a2ee705a7cd116d7029dc1
