### ISSUE TITLE
Update screenshots on the preferences section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#316]
### Description

update screenshots in this section https://docs.daily.dev/docs/customize-your-feed/preferences

**Comment by Gokilp** [comment]
can you please assign to me

**Comment by FrancescoXX** [comment]
assigned thank you!

**Comment by Gokilp** [comment]
thank you

**Comment by FrancescoXX** [comment]
done by https://github.com/dailydotdev/docs/commit/434d663606aef083c1a2ee705a7cd116d7029dc1
