### ISSUE TITLE
Check and list all the screenshots that needs to be updated

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#317]
### Description

We made a revamp of our Readign streak, so now we should check all the sections and point out when the screenshots need to be updated

https://docs.daily.dev/docs/intro

**Comment by Gokilp** [comment]
can you please assign to me

**Comment by FrancescoXX** [comment]
assigned to you @Gokilp

**Comment by FrancescoXX** [comment]
@Gokilp do you still want to work on this?
