### ISSUE TITLE
[UI] Post title font face

### ISSUE THREAD

**Issue by nabinkatwal7** [dailydotdev/docs#321]
### Description

Linux: The web extension takes in default font face, so if I pick a weird font the extension looks visually bad(refer screenshot), Wouldn't it be better if the title used pre defined font face? The font face I am using is Bevellier.

### Screenshots

![Screenshot from 2024-06-10 13-58-26](https://github.com/dailydotdev/docs/assets/91274113/356d3d4d-8eef-48e5-b310-e8baf30004e5)

**Comment by FrancescoXX** [comment]
thanks @nabinkatwal7 , would you be interested in working on this?

**Comment by nabinkatwal7** [comment]
of course. I would be glad to.

**Comment by FrancescoXX** [comment]
hey, @nabinkatwal7 , are you still interested in working on this?

**Comment by nabinkatwal7** [comment]
yes. I just could not find the repo related to it. Could you please drop a link to it?

**Comment by FrancescoXX** [comment]
what repository are you talking about?

**Comment by FrancescoXX** [comment]
@nabinkatwal7 do you still want to work on this? we are also in Hacktoberfest

**Comment by FrancescoXX** [comment]
@nabinkatwal7 this is not related to docs
