### ISSUE TITLE
[Update Squads section]

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#346]
### Description

Update squads section, also based on the upcoming squads' post

**Comment by Chirag8023** [comment]
I did some minor typo and formatting changes in the docs

**Comment by FrancescoXX** [comment]
gey @Chirag8023 do you still want to work on this?

**Comment by Chirag8023** [comment]
ohh, i did a rookie mistake, i deleted my fork before PR merged 😅
I'm sending new PR right away
