### ISSUE TITLE
Update Creating personal feed

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#349]
### Description

update this section, pics and section

http://localhost:3000/docs/setting-up-your-feed/filtering-content-feed

**Comment by tmsagarofficial** [comment]
I would love to work on this issue once assigned @FrancescoXX

**Comment by FrancescoXX** [comment]
go for it, thank you!

**Comment by FrancescoXX** [comment]
this has been solved for now https://github.com/dailydotdev/docs/commit/434d663606aef083c1a2ee705a7cd116d7029dc1
