### ISSUE TITLE
There is no daily.dev addon on addons.mozilla.org

### ISSUE THREAD

**Issue by skamansam** [dailydotdev/docs#350]
### Description

The docs at https://docs.daily.dev/docs/getting-started/browser-extension-installation has a link to a Firefox addon, but it links to a nonexitant page. 

Even after searching the addons site, I can't find it.

### Screenshots

![image](https://github.com/user-attachments/assets/8e50312d-cacc-417d-94e5-3b6650c64dc8)

### Additional information

Perhaps there is no firefox extension so this link should be removed.

**Comment by nimrodkra** [comment]
True, sorry about that. I've updated the docs accordingly with an explanation: 
![Screenshot 2024-08-05 at 10 14 11](https://github.com/user-attachments/assets/cc49d448-1d77-4f2d-a0a6-b446a7c4835b)
