### ISSUE TITLE
IMPROVE the design of the first page

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#360]
### Description

The design of the first page doesn't look good enough. We can create something inspired by the daily.dev design and create something way better

![image](https://github.com/user-attachments/assets/1aefdd80-ad35-4d14-ba8e-627b1700f6f3)

**Comment by pvishalkeerthan** [comment]
@FrancescoXX  Would like to work on this

**Comment by FrancescoXX** [comment]
please go on with the suggestions @pvishalkeerthan , you cna also create some issues and then we will decide if we want to implement them
