### ISSUE TITLE
Add a star counter on the top right

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#361]
### Description

add a github star counter on the top right, to showcase the number of stars of the project

![image](https://github.com/user-attachments/assets/495d028d-e830-45c1-8b4d-6190db6f6414)

**Comment by Chirag8023** [comment]
assign me

**Comment by FrancescoXX** [comment]
assigned!

**Comment by FrancescoXX** [comment]
@Chirag8023 do you still want to work on it?

**Comment by Chirag8023** [comment]
on it...
