### ISSUE TITLE
Update delete your account section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#378]
### Description

https://docs.daily.dev/docs/your-profile/deleting-your-profile

**Comment by FrancescoXX** [comment]
add pictures to the process

**Comment by mutant138** [comment]
Kindly assign to me

**Comment by Chaitra-kshirsagar** [comment]
@FrancescoXX I would like to work on this, assign it to me

**Comment by FrancescoXX** [comment]
@Chaitra-kshirsagar
