### ISSUE TITLE
Update the changelog link

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#383]
### Description

Update the current changelog link with this one: https://app.daily.dev/squads/daily_updates

![image](https://github.com/user-attachments/assets/a8772a19-178e-4c10-a52e-7b22f88b42a2)

**Comment by FrancescoXX** [comment]
the link is at the bottom of the page

**Comment by jasonetorres** [comment]
yup I will take this one too please lol

**Comment by jasonetorres** [comment]
@FrancescoXX can you point me to the file this needs to be changed in?

**Comment by FrancescoXX** [comment]
thanks @jasonetorres
