### ISSUE TITLE
Update stats of downloads, sources, users, caption on the first page

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#384]
### Description

https://docs.daily.dev/docs/intro

![image](https://github.com/user-attachments/assets/98facf27-da53-498b-aa97-06a71ae37bd0)

**Comment by lmfaolmaolol** [comment]
I would like to work on this, could you please guide me?

**Comment by FrancescoXX** [comment]
@lmfaolmaolol you can use the Twitter's bio 

something like this:

1 in 50 developers worldwide is staying up to date with [http://daily.dev](https://t.co/X5nzZaiIQ5). Being part of the other 49 might sound cool, but it’s not.

**Comment by lmfaolmaolol** [comment]
Thank you, i have made the changes and submitted the pull request. Also could you please add the hacktober fest label to this issue?

**Comment by FrancescoXX** [comment]
the repo si already tagged as hacktoberfest
