### ISSUE TITLE
Update the community page

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#385]
### Description

check the links and add the link to Linkedin

https://docs.daily.dev/docs/community

**Comment by FrancescoXX** [comment]
linkedin link to add:
https://www.linkedin.com/company/dailydotdev

**Comment by jasonetorres** [comment]
I willt ake this one too why not lol

**Comment by jasonetorres** [comment]
https://github.com/dailydotdev/docs/pull/396
