### ISSUE TITLE
Update Card UI

### ISSUE THREAD

**Issue by pvishalkeerthan** [dailydotdev/docs#389]
### Description

Present Card doesn't have hover effect and animations.Would like to Work on improving this to make it more attractive .

### Screenshots

![image](https://github.com/user-attachments/assets/daf9ec78-dde4-4980-b4c2-78286fbd83a1)

### Additional information

Would like to make it as Next docs or other any better UI you would recommend
![Uploading image.png…]()

**Comment by pvishalkeerthan** [comment]
@FrancescoXX  Would like to work on this

**Comment by lmfaolmaolol** [comment]
I would like to work on this

**Comment by FrancescoXX** [comment]
assigned to @pvishalkeerthan

**Comment by pvishalkeerthan** [comment]
@FrancescoXX I’ve kept the pull request for the Update Card UI. Looking forward to your feedback!

**Comment by FrancescoXX** [comment]
thank you!
