### ISSUE TITLE
Update the screenshot of the "Content and Language Filtering" section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#392]
### Description

The screenshot on the "Content and Language Filtering" section is not correct

link
https://docs.daily.dev/docs/setting-up-your-feed/advanced-filtering-options

wrong one:
![image](https://github.com/user-attachments/assets/65f65a37-44f9-433d-9d80-6c1c4e700e9d)

The correct screenshot is this one 
![image](https://github.com/user-attachments/assets/8e4c5141-3109-46f2-a88a-15d9a93c7fdf)

**Comment by jasonetorres** [comment]
assign me to this?

**Comment by FrancescoXX** [comment]
done

**Comment by FrancescoXX** [comment]
closed by #395 395
