### ISSUE TITLE
Adding links to privacy policy and terms of service.

### ISSUE THREAD

**Issue by developer-diganta** [dailydotdev/docs#40]
I think it would be helpful if these two were directly linked to their respective pages..
![image](https://user-images.githubusercontent.com/65999534/148523707-02165971-abe7-4826-94aa-030bc3221e15.png)

**Comment by FrancescoXX** [comment]
Thank you for noticing this

**Comment by developer-diganta** [comment]
@FrancescoXX  If it is ok, can I work on this?

**Comment by nimrodkra** [comment]
@developer-diganta Sure, go ahead! The links are:
1. Terms of service: https://daily.dev/tos
2. Privacy: https://daily.dev/privacy
