### ISSUE TITLE
Showing error with the username for New User

### ISSUE THREAD

**Issue by get-rishabh** [dailydotdev/docs#400]
### Description

There is no specific rules and conditions explicitly mentioned for the usernames.
Like, Are Special Characters like _, @, -, $, allowed or not
After many attempts, I figured it out my self that, there should be no, Special Characters.
But it should be explicitly mentioned.

### Screenshots

![image](https://github.com/user-attachments/assets/2985c86e-3103-4c01-98a0-b3c3b13ba669)

**Comment by get-rishabh** [comment]
@FrancescoXX  Could you please add the relevant label to this issue?

**Comment by FrancescoXX** [comment]
hey @PredictiveManish , this is the docs section, so we can mention it, but again these are just the docs, not the app

**Comment by PredictiveManish** [comment]
@FrancescoXX Thanks for assigning this task!

**Comment by PredictiveManish** [comment]
@FrancescoXX Found out the error message and updated and changed it in my forked repo and during pushing it to main repo can you help me out How can i link that PR into this issue as these both are in different sources. Thanks in advance!

**Comment by PredictiveManish** [comment]
Solved and made PR-  https://github.com/dailydotdev/apps/pull/3661 @FrancescoXX Please check it out and if possible merge it after checking it, and tell me if I have to do anything more.

**Comment by FrancescoXX** [comment]
this is not related ot the docs but the app itself
