### ISSUE TITLE
ADD Comment sorting section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#402]
### Description

Update the docs based on this

https://dly.to/G5diOf5JQyV

**Comment by PredictiveManish** [comment]
Working on this!! /assign

**Comment by FrancescoXX** [comment]
done @PredictiveManish

**Comment by PredictiveManish** [comment]
> done @PredictiveManish

Okk @FrancescoXX

**Comment by PredictiveManish** [comment]
Will definitely this by tomorrow.

**Comment by PredictiveManish** [comment]
@FrancescoXX Solved in #438. Please advise me if any changes required.
