### ISSUE TITLE
Search Users

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#403]
### Description

https://dly.to/0TN4Cypa7pN

**Comment by PredictiveManish** [comment]
Can you elaborate a little more about this I didn't got the point!!

**Comment by PredictiveManish** [comment]
@FrancescoXX Updated this in #437

**Comment by PredictiveManish** [comment]
> ### Description
> https://dly.to/0TN4Cypa7pN
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Updated this in #437
