### ISSUE TITLE
create leaderboard section

### ISSUE THREAD

**Issue by FrancescoXX** [dailydotdev/docs#426]
### Description

create leaderboard section

**Comment by sabdailydev** [comment]
The document is [here](https://docs.google.com/document/d/1EVpfEqDj6ByQ2X-zcNK_Shoh9uWZgapQXGbb1v4Z9LU/edit?tab=t.0#heading=h.4etlnbdhdnut)

**Comment by FrancescoXX** [comment]
closed by #439
