### ISSUE TITLE
Replacing a full stop with an exclamation sign

### ISSUE THREAD

**Issue by sumitsaurabh927** [dailydotdev/docs#86]
I think an exclamation mark after a new user installs the extension captures the excitement better!

So, it should be `Just install it, open a new tab, and you're all set!` like how it is for `Try our progressive web app!`
![image](https://user-images.githubusercontent.com/62152915/179098996-db7e6cba-0993-4fad-8e82-733623aebbdb.png)

**Comment by nimrodkra** [comment]
Hi Sumit,

Would you like to submit a PR to improve it?

**Comment by sumitsaurabh927** [comment]
Hey Nimrod! I've already opened a PR for this #87
