### ISSUE TITLE
Phrases could be combined for better reading.

### ISSUE THREAD

**Issue by Njong392** [dailydotdev/docs#97]
In the progressive web app section, (here specifically https://docs.daily.dev/docs/getting-started/pwa#how-can-i-add-dailydev-to-my-mobile-home-screen-on-ios) there are two following phrases.
`For iOS users, you can add a website icon to your iPhone Home Screen!`
`You can add a website icon to your iPhone Home Screen for quick access to that site.`

They both almost read the same, and I think merging the two would sort of make it read better. Something along the lines of,
`For iOS users, you can add a website icon to your iPhone Home screen for quick access to that site.`

**Comment by GrahamTheDev** [comment]
100% agree, do you want to take this one as well?

Suggested final phrasing:

"For iOS users, you can add a shortcut to your iPhone Home screen for quick access to the daily.dev web app!"
