### ISSUE TITLE
Question mark required

### ISSUE THREAD

**Issue by Njong392** [dailydotdev/docs#98]
## Link 
https://docs.daily.dev/docs/settingyourfeed/filtering-content-feed#choose-tags
## Issue
a) Point 3 talks about searching tags. A phrase there reads `Didn't find the tag you were looking for, use the search to find...`
b) The `info` quote card just after point 3 mentioned above has text along the lines of `Wondering how does daily.dev classify articles?  Learn more about...`
## Proposed changes
for a) After `Didn't find the tag you were looking for` I think there should be a question mark before continuing with `use the search to find...` That way, the phrase can read as `Didn't find the tag you were looking for? Use the search to find...`

for b) Suggesting that the aforementioned be rephrased to `Wondering how daily.dev classifies articles?  Learn more about...`

**Comment by GrahamTheDev** [comment]
And I agree with this one too. 

Do you want to raise a PR?
