### ISSUE TITLE
Typo in table

### ISSUE THREAD

**Issue by Njong392** [dailydotdev/docs#99]
## Link
https://docs.daily.dev/docs/settingyourfeed/advanced-filtering-options#available-content-categories

## Issue
On the table, in the second column, under the description of  `Non-editorial content`, it says "Show user-generated posts that **we're** created on external blogging platforms"

## Proposed changes
The word **we're** should be changed to **were** to fit the context, so that phrase reads as "Show user-generated posts that **were** created on external blogging platforms"

**Comment by GrahamTheDev** [comment]
Do you want to take this for a green square?

**Comment by Njong392** [comment]
> Do you want to take this for a green square?

Sure. I'll take it. And the rest of the other issues that are still open I guess haha

**Comment by GrahamTheDev** [comment]
All the typos that you raised are yours if you want them! I have left comments on each 👍
